<a href="https://colab.research.google.com/github/delowerhossentuhin/Computer-Vision-and-Pattern-Recognition-/blob/main/00_Tensorflow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_zero_D = tf.constant(8)
print(tensor_zero_D)

tf.Tensor(8, shape=(), dtype=int32)


In [3]:
tensor_one_D = tf.constant([3,4,5,6,7])
print(tensor_one_D)

tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)


In [4]:
tensor_one_D = tf.constant(np.zeros(5))
print(tensor_one_D)

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float64)


In [5]:
tensor_one_D = tf.constant(np.ones(5))
print(tensor_one_D)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float64)


In [6]:
tensor_two_D = tf.constant(np.full(2,8))
print(tensor_two_D)

tf.Tensor([8 8], shape=(2,), dtype=int64)


In [7]:
tensor_multi_D = tf.constant(np.full((4,2,6),np.array([1,-2,3,-4,5,-6])), dtype=tf.float32)
print(tensor_multi_D)

tf.Tensor(
[[[ 1. -2.  3. -4.  5. -6.]
  [ 1. -2.  3. -4.  5. -6.]]

 [[ 1. -2.  3. -4.  5. -6.]
  [ 1. -2.  3. -4.  5. -6.]]

 [[ 1. -2.  3. -4.  5. -6.]
  [ 1. -2.  3. -4.  5. -6.]]

 [[ 1. -2.  3. -4.  5. -6.]
  [ 1. -2.  3. -4.  5. -6.]]], shape=(4, 2, 6), dtype=float32)


In [8]:
print(tensor_multi_D.shape)

(4, 2, 6)


In [9]:
print(tensor_multi_D.ndim)

3


**Casting**


---


***In TensorFlow (and NumPy, and Python),
any non-zero value → True,
zero → False.***

In [10]:
org_tensor = tf.constant(np.full((4,2,6),np.array([1,-2,3,-4,0,-6])), dtype=tf.float32)
print(org_tensor)
cast_tensor = tf.cast(org_tensor,dtype=tf.int64)
print(cast_tensor)
cast_tensor = tf.cast(cast_tensor,dtype=tf.bool)
print(cast_tensor)

tf.Tensor(
[[[ 1. -2.  3. -4.  0. -6.]
  [ 1. -2.  3. -4.  0. -6.]]

 [[ 1. -2.  3. -4.  0. -6.]
  [ 1. -2.  3. -4.  0. -6.]]

 [[ 1. -2.  3. -4.  0. -6.]
  [ 1. -2.  3. -4.  0. -6.]]

 [[ 1. -2.  3. -4.  0. -6.]
  [ 1. -2.  3. -4.  0. -6.]]], shape=(4, 2, 6), dtype=float32)
tf.Tensor(
[[[ 1 -2  3 -4  0 -6]
  [ 1 -2  3 -4  0 -6]]

 [[ 1 -2  3 -4  0 -6]
  [ 1 -2  3 -4  0 -6]]

 [[ 1 -2  3 -4  0 -6]
  [ 1 -2  3 -4  0 -6]]

 [[ 1 -2  3 -4  0 -6]
  [ 1 -2  3 -4  0 -6]]], shape=(4, 2, 6), dtype=int64)
tf.Tensor(
[[[ True  True  True  True False  True]
  [ True  True  True  True False  True]]

 [[ True  True  True  True False  True]
  [ True  True  True  True False  True]]

 [[ True  True  True  True False  True]
  [ True  True  True  True False  True]]

 [[ True  True  True  True False  True]
  [ True  True  True  True False  True]]], shape=(4, 2, 6), dtype=bool)


***Identity Matrix using eye method***

In [11]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=7,
    batch_shape=(3,),
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]]], shape=(3, 4, 7), dtype=float32)


**tf.fill method**

In [12]:
fill_tensor = tf.fill((3,4),9.)
print(fill_tensor)

tf.Tensor(
[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]], shape=(3, 4), dtype=float32)


In [14]:
ones_like_tensor = tf.ones_like(org_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(4, 2, 6), dtype=float32)


*https://www.acsu.buffalo.edu/~adamcunn/probability/normal.html*

In [23]:
random_tensor = tf.random.normal(
    shape = (3,4),
    mean=100.0,
    stddev=10.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 97.524414  95.859955 110.45157   81.843   ]
 [ 91.66758   97.927574 111.76755   93.38109 ]
 [ 93.41674  106.40996  100.98981  114.227745]], shape=(3, 4), dtype=float32)


In [24]:
tf.random.uniform(
    shape = (3,2),
    minval=0,
    maxval=10,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.9011545, 9.234339 ],
       [7.936445 , 8.059598 ],
       [6.4824953, 2.6811206]], dtype=float32)>